envName: test

default:
  app:
    destination:
      namespace: test
      server: https://kubernetes.default.svc
    source:
      targetRevision: test


applications:
  pdf-service:
    enabled: true
    enableAutoSync: true

  mailqueue:
    enabled: true
    enableAutoSync: true

  api-gateway:
    enabled: true
    enableAutoSync: true

  auth-service:
    enabled: true
    enableAutoSync: true