envName: production

default:
  app:
    destination:
      namespace: production
      server: https://kubernetes.default.svc
    project: infra
    source:
      targetRevision: production


applications:
  k8s-service-accounts:
    enabled: true
    enableAutoSync: true

  service-discovery:
    enabled: true
    enableAutoSync: true

  infra-svc:
    enabled: true
    enableAutoSync: true
